CREATE DATABASE EMPRESA_Z;
USE EMPRESA_Z

CREATE TABLE CLIENTES(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,	/*CRIANDO UMA PK*/
	NOME VARCHAR(50) NOT NULL,
	ENDERECO VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50),
	DATA_NASCIMENTO DATETIME

	/*CONSTRAINT PK_PRODUTOS PRIMARY KEY (ID)*/			/*OUTRA FORMA DE CRIAR UM PK*/
)

ALTER TABLE CLIENTES ALTER COLUMN DATA_NASCIMENTO DATE
SP_HELP CLIENTES

INSERT INTO CLIENTES(NOME, ENDERECO, EMAIL, DATA_NASCIMENTO)
VALUES ('Teste da Silva', 'Rua testadora nogueira', 'testando@email.com', '2000-01-09')

SELECT	*
FROM	CLIENTES

DROP TABLE CLIENTES

/* MOSTRANDO TODAS AS TABELAS DE UMA DB */
SELECT	*
FROM	INFORMATION_SCHEMA.TABLES



CREATE TABLE PRODUTOS(
	ID INT IDENTITY(1,1) NOT NULL,
	PRODUTO VARCHAR(50) NOT NULL, 
	QUANTIDADE INT NOT NULL,
	PRECO DECIMAL(18, 2) NOT NULL,
	
	CONSTRAINT PK_PRODUTOS PRIMARY KEY (ID)
)

INSERT INTO PRODUTOS(PRODUTO, QUANTIDADE, PRECO)
VALUES ('Danoteste', 30, 20.50)

DELETE FROM PRODUTOS 

DBCC CHECKIDENT ('PRODUTOS', RESEED, 0)  

SELECT *
FROM PRODUTOS

DROP TABLE PRODUTOS
SP_HELP PRODUTOS



CREATE TABLE PEDIDO(
	ID_PEDIDO INT IDENTITY (1,1) NOT NULL,
	ID_PRODUTO INT CONSTRAINT FK_PRODUTO REFERENCES PRODUTOS(ID),	/*CRIANDO UMA FK*/
	ID_CLIENTE INT,
	QUANTIDADE INT,

	CONSTRAINT PK_PEDIDO PRIMARY KEY(ID_PEDIDO),
	/*CONSTRAINT FK_PRODUTO FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTOS(ID),*/		/*OUTRA FORMA DE FAZER UMA FK*/
	CONSTRAINT FK_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID)
	
)

SELECT *
FROM PEDIDO

DELETE FROM PEDIDO

DBCC CHECKIDENT('PEDIDO', RESEED, 0)

INSERT INTO PEDIDO(ID_PRODUTO, ID_CLIENTE, QUANTIDADE)
VALUES (1, 1, 10)


ALTER TABLE PEDIDO ADD VALIDADE DATE NOT NULL DEFAULT '2008-01-01'

ALTER TABLE PEDIDO ADD ID_VENDEDOR INT 

ALTER TABLE PEDIDO ADD CONSTRAINT FK_VENDEDOR
FOREIGN KEY(ID_VENDEDOR) REFERENCES VENDEDOR(ID)


CREATE TABLE VENDEDOR(
	ID INT IDENTITY (1,1) NOT NULL,
	NOME VARCHAR(50),

	CONSTRAINT PK_VENDEDOR PRIMARY KEY (ID)
)







DROP TABLE VENDEDOR
SP_HELP PEDIDO 

